CC = gcc
SOURCES_SERVER = src/server.cpp
OBJECTS_SERVER = $(SOURCES_SERVER:.cpp=.o)
EXECUTABLE_SERVER = server
SOURCES_CLIENT = src/client.cpp
OBJECTS_CLIENT = $(SOURCES_CLIENT:.cpp=.o)
EXECUTABLE_CLIENT = client
BUILD_DIR = build
LDFLAGS = -lstdc++

all: $(BUILD_DIR) $(EXECUTABLE_SERVER) $(EXECUTABLE_CLIENT)

$(EXECUTABLE_SERVER): $(OBJECTS_SERVER)
	$(CC) $(OBJECTS_SERVER) $(LDFLAGS) -o $(BUILD_DIR)/$@

$(EXECUTABLE_CLIENT): $(OBJECTS_CLIENT)
	$(CC) $(OBJECTS_CLIENT) $(LDFLAGS) -o $(BUILD_DIR)/$@

%.o: %.cpp
	$(CC) -c $< -o $@

clean:
	rm -rf $(OBJECTS_SERVER) $(OBJECTS_CLIENT) $(BUILD_DIR)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

.PHONY: $(BUILD_DIR)

$(EXECUTABLE_SERVER)-run: $(EXECUTABLE_SERVER)
	$(BUILD_DIR)/$(EXECUTABLE_SERVER)

$(EXECUTABLE_CLIENT)-run: $(EXECUTABLE_CLIENT)
	$(BUILD_DIR)/$(EXECUTABLE_CLIENT)
